### ISSUE TITLE
Add ReleaseNotes property to properties list

### ISSUE THREAD

**Issue by oppositional** [matthewethomas/VSTS_NetStandardProjectVars#2]
I would like to write the ReleaseNotes property of my .csproj file but currently the Write Project Property task does not provide it as a selectable option.

**Comment by SemaphoreSlim1** [comment]
@oppositional , try selecting custom as the property, and then putting in ReleaseNotes - does that work for you?

**Comment by SemaphoreSlim1** [comment]
I'm assuming silence means yes. 😉
